local LSM = LibStub("LibSharedMedia-3.0") 

-- ----- 
-- BACKGROUND 
-- ----- 

-- ----- 
--  BORDER 
-- ---- 

-- -----
--   FONT
-- -----

-- -------------------
--   SOUND
-- -------------------

----------- Numbers------------
LSM:Register("sound", "|cff00ff00--Numbers--|r", [[Interface\Addons\SharedMedia_ONS\sound\PLACEHOLDER.mp3]])
LSM:Register("sound", "|cff00ff001|r", [[Interface\Addons\SharedMedia_ONS\sound\01_1.mp3]])
LSM:Register("sound", "|cff00ff002|r", [[Interface\Addons\SharedMedia_ONS\sound\02_2.mp3]])
LSM:Register("sound", "|cff00ff003|r", [[Interface\Addons\SharedMedia_ONS\sound\03_3.mp3]])
LSM:Register("sound", "|cff00ff004|r", [[Interface\Addons\SharedMedia_ONS\sound\04_4.mp3]])
LSM:Register("sound", "|cff00ff005|r", [[Interface\Addons\SharedMedia_ONS\sound\05_5.mp3]])
LSM:Register("sound", "|cff00ff006|r", [[Interface\Addons\SharedMedia_ONS\sound\06_6.mp3]])
LSM:Register("sound", "|cff00ff007|r", [[Interface\Addons\SharedMedia_ONS\sound\07_7.mp3]])
LSM:Register("sound", "|cff00ff008|r", [[Interface\Addons\SharedMedia_ONS\sound\08_8.mp3]])
LSM:Register("sound", "|cff00ff009|r", [[Interface\Addons\SharedMedia_ONS\sound\09_9.mp3]])
LSM:Register("sound", "|cFFFE000010|r", [[Interface\Addons\SharedMedia_ONS\sound\10_10.mp3]])

---------- Markers ------------
LSM:Register("sound", "|cff00ff00Skull|r", [[Interface\Addons\SharedMedia_ONS\sound\11_skull.mp3]])
LSM:Register("sound", "|cff00ff00Cross|r", [[Interface\Addons\SharedMedia_ONS\sound\12_cross.mp3]])
LSM:Register("sound", "|cff00ff00Square|r", [[Interface\Addons\SharedMedia_ONS\sound\13_Square.mp3]])
LSM:Register("sound", "|cff00ff00Moon|r", [[Interface\Addons\SharedMedia_ONS\sound\14_Moon.mp3]])
LSM:Register("sound", "|cff00ff00Triangle|r", [[Interface\Addons\SharedMedia_ONS\sound\15_Triangle.mp3]])
LSM:Register("sound", "|cff00ff00Diamond|r", [[Interface\Addons\SharedMedia_ONS\sound\16_Diamond.mp3]])
LSM:Register("sound", "|cff00ff00Circle|r", [[Interface\Addons\SharedMedia_ONS\sound\17_Circle.mp3]])
LSM:Register("sound", "|cff00ff00Star|r", [[Interface\Addons\SharedMedia_ONS\sound\18_Star.mp3]])

----------- Icons -------------
LSM:Register("sound", "|cff00ff00ADDS|r", [[Interface\Addons\SharedMedia_ONS\sound\20_Adds.mp3]])
LSM:Register("sound", "|cff00ff00AOE|r", [[Interface\Addons\SharedMedia_ONS\sound\21_AOE.mp3]])
LSM:Register("sound", "|cff00ff00Assist|r", [[Interface\Addons\SharedMedia_ONS\sound\22_Assist.mp3]])
LSM:Register("sound", "|cff00ff00Avoid|r", [[Interface\Addons\SharedMedia_ONS\sound\23_Avoid.mp3]])
LSM:Register("sound", "|cff00ff00Back|r", [[Interface\Addons\SharedMedia_ONS\sound\24_Back.mp3]])
LSM:Register("sound", "|cff00ff00Backup|r", [[Interface\Addons\SharedMedia_ONS\sound\25_Backup.mp3]])
LSM:Register("sound", "|cff00ff00Bait|r", [[Interface\Addons\SharedMedia_ONS\sound\26_Bait.mp3]])
LSM:Register("sound", "|cff00ff00Beam|r", [[Interface\Addons\SharedMedia_ONS\sound\27_Beam.mp3]])
LSM:Register("sound", "|cff00ff00Bloodlust|r", [[Interface\Addons\SharedMedia_ONS\sound\28_BloodLust.mp3]])
LSM:Register("sound", "|cff00ff00Blue|r", [[Interface\Addons\SharedMedia_ONS\sound\29_Blue.mp3]])
LSM:Register("sound", "|cff00ff00Boss|r", [[Interface\Addons\SharedMedia_ONS\sound\30_Boss.mp3]])
LSM:Register("sound", "|cff00ff00Break|r", [[Interface\Addons\SharedMedia_ONS\sound\31_Break.mp3]])
LSM:Register("sound", "|cff00ff00Buff|r", [[Interface\Addons\SharedMedia_ONS\sound\32_Buff.mp3]])
LSM:Register("sound", "|cff00ff00CC|r", [[Interface\Addons\SharedMedia_ONS\sound\33_CC.mp3]])
LSM:Register("sound", "|cff00ff00CD|r", [[Interface\Addons\SharedMedia_ONS\sound\34_CD.mp3]])
LSM:Register("sound", "|cff00ff00Centre|r", [[Interface\Addons\SharedMedia_ONS\sound\35_Centre.mp3]])
LSM:Register("sound", "|cff00ff00Chain|r", [[Interface\Addons\SharedMedia_ONS\sound\36_Chain.mp3]])
LSM:Register("sound", "|cff00ff00Charge|r", [[Interface\Addons\SharedMedia_ONS\sound\37_Charge.mp3]])
LSM:Register("sound", "|cff00ff00Clear|r", [[Interface\Addons\SharedMedia_ONS\sound\38_Clear.mp3]])
LSM:Register("sound", "|cff00ff00Collect|r", [[Interface\Addons\SharedMedia_ONS\sound\39_Collect.mp3]])
LSM:Register("sound", "|cff00ff00Collected|r", [[Interface\Addons\SharedMedia_ONS\sound\40_Collected.mp3]])
LSM:Register("sound", "|cff00ff00Dance|r", [[Interface\Addons\SharedMedia_ONS\sound\41_Dance.mp3]])
LSM:Register("sound", "|cff00ff00Debuff|r", [[Interface\Addons\SharedMedia_ONS\sound\42_Debuff.mp3]])
LSM:Register("sound", "|cff00ff00Dispel|r", [[Interface\Addons\SharedMedia_ONS\sound\43_Dispel.mp3]])
LSM:Register("sound", "|cff00ff00Dodge|r", [[Interface\Addons\SharedMedia_ONS\sound\44_Dodge.mp3]])
LSM:Register("sound", "|cff00ff00Dont Move|r", [[Interface\Addons\SharedMedia_ONS\sound\45_DontMove.mp3]])
LSM:Register("sound", "|cff00ff00DOT|r", [[Interface\Addons\SharedMedia_ONS\sound\46_DOT.mp3]])
LSM:Register("sound", "|cff00ff00DROP|r", [[Interface\Addons\SharedMedia_ONS\sound\47_DROP.mp3]])
LSM:Register("sound", "|cff00ff00ENTER|r", [[Interface\Addons\SharedMedia_ONS\sound\48_ENTER.mp3]])
LSM:Register("sound", "|cff00ff00ESCORT|r", [[Interface\Addons\SharedMedia_ONS\sound\49_ESCORT.mp3]])
LSM:Register("sound", "|cff00ff00EXIT|r", [[Interface\Addons\SharedMedia_ONS\sound\50_EXIT.mp3]])
LSM:Register("sound", "|cff00ff00Fixate|r", [[Interface\Addons\SharedMedia_ONS\sound\51_Fixate.mp3]])
LSM:Register("sound", "|cff00ff00Front|r", [[Interface\Addons\SharedMedia_ONS\sound\52_Front.mp3]])
LSM:Register("sound", "|cff00ff00Gate|r", [[Interface\Addons\SharedMedia_ONS\sound\53_Gate.mp3]])
LSM:Register("sound", "|cff00ff00Gather|r", [[Interface\Addons\SharedMedia_ONS\sound\54_Gather.mp3]])
LSM:Register("sound", "|cff00ff00Taunt|r", [[Interface\Addons\SharedMedia_ONS\sound\55_Taunt.mp3]])
LSM:Register("sound", "|cff00ff00GO|r", [[Interface\Addons\SharedMedia_ONS\sound\56_GO.mp3]])
LSM:Register("sound", "|cff00ff00Stop|r", [[Interface\Addons\SharedMedia_ONS\sound\57_Stop.mp3]])
LSM:Register("sound", "|cff00ff00Posion|r", [[Interface\Addons\SharedMedia_ONS\sound\58_Posion.mp3]])
LSM:Register("sound", "|cff00ff00Fire|r", [[Interface\Addons\SharedMedia_ONS\sound\59_Fire.mp3]])
LSM:Register("sound", "|cff00ff00Void Zone|r", [[Interface\Addons\SharedMedia_ONS\sound\60_VoidZone.mp3]])
LSM:Register("sound", "|cff00ff00Flare Bomb|r", [[Interface\Addons\SharedMedia_ONS\sound\61_FlareBomb.mp3]])
LSM:Register("sound", "|cff00ff00Feast Down|r", [[Interface\Addons\SharedMedia_ONS\sound\62_FeastDown.mp3]])
LSM:Register("sound", "|cff00ff00Buffs Missing|r", [[Interface\Addons\SharedMedia_ONS\sound\63_BuffsMissing.mp3]])
LSM:Register("sound", "|cff00ff00Soak|r", [[Interface\Addons\SharedMedia_ONS\sound\64_Soak.mp3]])
LSM:Register("sound", "|cff00ff00Dont Soak|r", [[Interface\Addons\SharedMedia_ONS\sound\65_DontSoak.mp3]])
LSM:Register("sound", "|cff00ff00Red|r", [[Interface\Addons\SharedMedia_ONS\sound\66_Red.mp3]])
LSM:Register("sound", "|cff00ff00Blue|r", [[Interface\Addons\SharedMedia_ONS\sound\67_Blue.mp3]])
LSM:Register("sound", "|cff00ff00Green|r", [[Interface\Addons\SharedMedia_ONS\sound\68_Green.mp3]])
LSM:Register("sound", "|cff00ff00Purple|r", [[Interface\Addons\SharedMedia_ONS\sound\69_Purple.mp3]])
LSM:Register("sound", "|cff00ff00Orange|r", [[Interface\Addons\SharedMedia_ONS\sound\70_Orange.mp3]])
LSM:Register("sound", "|cff00ff00White|r", [[Interface\Addons\SharedMedia_ONS\sound\71_White.mp3]])
LSM:Register("sound", "|cff00ff00Gray|r", [[Interface\Addons\SharedMedia_ONS\sound\72_Gray.mp3]])
LSM:Register("sound", "|cff00ff00Yellow|r", [[Interface\Addons\SharedMedia_ONS\sound\73_Yellow.mp3]])
LSM:Register("sound", "|cff00ff00Follow|r", [[Interface\Addons\SharedMedia_ONS\sound\74_Follow.mp3]])
LSM:Register("sound", "|cff00ff00MountUp|r", [[Interface\Addons\SharedMedia_ONS\sound\75_MountUp.mp3]])
LSM:Register("sound", "|cff00ff00Personals|r", [[Interface\Addons\SharedMedia_ONS\sound\76_Personals.mp3]])
LSM:Register("sound", "|cff00ff00Health Stone|r", [[Interface\Addons\SharedMedia_ONS\sound\77_HealthStone.mp3]])
LSM:Register("sound", "|cff00ff00Health Pot|r", [[Interface\Addons\SharedMedia_ONS\sound\78_HealthPot.mp3]])
LSM:Register("sound", "|cff00ff00Stack|r", [[Interface\Addons\SharedMedia_ONS\sound\79_Stack.mp3]])
LSM:Register("sound", "|cff00ff00Freedom|r", [[Interface\Addons\SharedMedia_ONS\sound\80_Freedom.mp3]])
LSM:Register("sound", "|cff00ff00Immunity|r", [[Interface\Addons\SharedMedia_ONS\sound\81_Immunity.mp3]])
LSM:Register("sound", "|cff00ff00Immune|r", [[Interface\Addons\SharedMedia_ONS\sound\82_Immune.mp3]])
LSM:Register("sound", "|cff00ff00Go Out|r", [[Interface\Addons\SharedMedia_ONS\sound\83_GoOut.mp3]])
LSM:Register("sound", "|cff00ff00Trance Eat|r", [[Interface\Addons\SharedMedia_ONS\sound\84_TranceEat.mp3]])

LSM:Register("sound", "|cff00ff00Seeds|r", [[Interface\Addons\SharedMedia_ONS\sound\85_Seeds.mp3]])
LSM:Register("sound", "|cff00ff00Drop Seeds|r", [[Interface\Addons\SharedMedia_ONS\sound\86_DropSeeds.mp3]])
LSM:Register("sound", "|cff00ff00Collect Seeds|r", [[Interface\Addons\SharedMedia_ONS\sound\87_CollectSeeds.mp3]])
LSM:Register("sound", "|cff00ff00Corrupted Seeds|r", [[Interface\Addons\SharedMedia_ONS\sound\88_CorruptedSeeds.mp3]])
LSM:Register("sound", "|cff00ff00Shields|r", [[Interface\Addons\SharedMedia_ONS\sound\89_Shields.mp3]])
LSM:Register("sound", "|cff00ff00Shield Gone|r", [[Interface\Addons\SharedMedia_ONS\sound\90_ShieldGone.mp3]])
LSM:Register("sound", "|cff00ff00Shield Up|r", [[Interface\Addons\SharedMedia_ONS\sound\91_ShieldUp.mp3]])
LSM:Register("sound", "|cff00ff00Shield Down|r", [[Interface\Addons\SharedMedia_ONS\sound\92_ShieldDown.mp3]])
LSM:Register("sound", "|cff00ff00Stack|r", [[Interface\Addons\SharedMedia_ONS\sound\93_Stack.mp3]])
LSM:Register("sound", "|cff00ff00Danger|r", [[Interface\Addons\SharedMedia_ONS\sound\94_Danger.mp3]])
LSM:Register("sound", "|cff00ff00Beams Incoming|r", [[Interface\Addons\SharedMedia_ONS\sound\95_BeamsIncoming.mp3]])
LSM:Register("sound", "|cff00ff00Spread|r", [[Interface\Addons\SharedMedia_ONS\sound\96_Spread.mp3]])
LSM:Register("sound", "|cff00ff00Move|r", [[Interface\Addons\SharedMedia_ONS\sound\97_Move.mp3]])
LSM:Register("sound", "|cff00ff00Pull|r", [[Interface\Addons\SharedMedia_ONS\sound\98_Pull.mp3]])
LSM:Register("sound", "|cff00ff00Targeted|r", [[Interface\Addons\SharedMedia_ONS\sound\99_Targeted.mp3]])
LSM:Register("sound", "|cff00ff00Target|r", [[Interface\Addons\SharedMedia_ONS\sound\100_Target.mp3]])
LSM:Register("sound", "|cff00ff00Orbs|r", [[Interface\Addons\SharedMedia_ONS\sound\101_Orbs.mp3]])
LSM:Register("sound", "|cff00ff00Orb|r", [[Interface\Addons\SharedMedia_ONS\sound\102_Orb.mp3]])
LSM:Register("sound", "|cff00ff00Gravity Bomb|r", [[Interface\Addons\SharedMedia_ONS\sound\103_GravityBomb.mp3]])
LSM:Register("sound", "|cff00ff00Bozo|r", [[Interface\Addons\SharedMedia_ONS\sound\104_Bozo.mp3]])
LSM:Register("sound", "|cff00ff00You Died|r", [[Interface\Addons\SharedMedia_ONS\sound\105_YouDied.mp3]])
LSM:Register("sound", "|cff00ff00Phase Change|r", [[Interface\Addons\SharedMedia_ONS\sound\106_PhaseChange.mp3]])
LSM:Register("sound", "|cff00ff00Phasing|r", [[Interface\Addons\SharedMedia_ONS\sound\107_Phasing.mp3]])
LSM:Register("sound", "|cff00ff00Phase One|r", [[Interface\Addons\SharedMedia_ONS\sound\108_PhaseOne.mp3]])
LSM:Register("sound", "|cff00ff00Phase Two|r", [[Interface\Addons\SharedMedia_ONS\sound\109_PhaseTwo.mp3]])
LSM:Register("sound", "|cff00ff00Phase Three|r", [[Interface\Addons\SharedMedia_ONS\sound\110_PhaseThree.mp3]])

------- V1.0.1 Sounds ------------
LSM:Register("sound", "|cff00ff00Intermission|r", [[Interface\Addons\SharedMedia_ONS\sound\111_Intermission.mp3]])
LSM:Register("sound", "|cff00ff00Intermission One|r", [[Interface\Addons\SharedMedia_ONS\sound\112_IntermissionOne.mp3]])
LSM:Register("sound", "|cff00ff00Intermission Two|r", [[Interface\Addons\SharedMedia_ONS\sound\113_IntermissionTwo.mp3]])
LSM:Register("sound", "|cff00ff00Intermission Three|r", [[Interface\Addons\SharedMedia_ONS\sound\114_IntermissionThree.mp3]])
LSM:Register("sound", "|cff00ff00Fixated|r", [[Interface\Addons\SharedMedia_ONS\sound\115_Fixated.mp3]])
LSM:Register("sound", "|cff00ff00High Energy|r", [[Interface\Addons\SharedMedia_ONS\sound\116_HighEnergy.mp3]])
LSM:Register("sound", "|cff00ff00High Stacks|r", [[Interface\Addons\SharedMedia_ONS\sound\117_HighStacks.mp3]])
LSM:Register("sound", "|cff00ff00Hide|r", [[Interface\Addons\SharedMedia_ONS\sound\118_Hide.mp3]])
LSM:Register("sound", "|cff00ff00Transition|r", [[Interface\Addons\SharedMedia_ONS\sound\119_Transition.mp3]])
LSM:Register("sound", "|cff00ff00Switch|r", [[Interface\Addons\SharedMedia_ONS\sound\120_Switch.mp3]])
LSM:Register("sound", "|cff00ff00Stop Casting|r", [[Interface\Addons\SharedMedia_ONS\sound\121_StopCasting.mp3]])
LSM:Register("sound", "|cff00ff00Jump|r", [[Interface\Addons\SharedMedia_ONS\sound\122_Jump.mp3]])
LSM:Register("sound", "|cff00ff00Totem|r", [[Interface\Addons\SharedMedia_ONS\sound\123_Totem.mp3]])
LSM:Register("sound", "|cff00ff00Trap|r", [[Interface\Addons\SharedMedia_ONS\sound\124_Trap.mp3]])
LSM:Register("sound", "|cff00ff00Pushback|r", [[Interface\Addons\SharedMedia_ONS\sound\125_Pushback.mp3]])
LSM:Register("sound", "|cff00ff00Winds|r", [[Interface\Addons\SharedMedia_ONS\sound\126_Winds.mp3]])
LSM:Register("sound", "|cff00ff00Pull|r", [[Interface\Addons\SharedMedia_ONS\sound\127_Pull.mp3]])

--------- V1.1.1 Sounds -----------
LSM:Register("sound", "|cff00ff00Viranyr Get Away|r", [[Interface\Addons\SharedMedia_ONS\sound\128_GetAwayFromMe.mp3]])
LSM:Register("sound", "|cff00ff00Cheeky Rogue|r", [[Interface\Addons\SharedMedia_ONS\sound\129_PeksLaugh.mp3]])

--------- Random Sounds --------
LSM:Register("sound", "|cff55ee55ark Souls Death|r", [[Interface\Addons\SharedMedia_ONS\sound\Z1_DarkSouls_Death.mp3]])
LSM:Register("sound", "|cff55ee55Skill Issue|r", [[Interface\Addons\SharedMedia_ONS\sound\Z2_SKillIssue.ogg]])
