local LSM = LibStub("LibSharedMedia-3.0")

-- -----
-- BACKGROUND
-- -----

-- -----
--  BORDER
-- ----

-- -----
--   FONT
-- -----




----------------------------------------------------------------
-----------------------------SOUNDS-----------------------------
----------------------------------------------------------------


----------- Numbers------------
LSM:Register("sound", "|cff00ff001|r", [[Interface\Addons\SharedMedia_ONS\sound\01_1.mp3]])
LSM:Register("sound", "|cff00ff002|r", [[Interface\Addons\SharedMedia_ONS\sound\02_2.mp3]])
LSM:Register("sound", "|cff00ff003|r", [[Interface\Addons\SharedMedia_ONS\sound\03_3.mp3]])
LSM:Register("sound", "|cff00ff004|r", [[Interface\Addons\SharedMedia_ONS\sound\04_4.mp3]])
LSM:Register("sound", "|cff00ff005|r", [[Interface\Addons\SharedMedia_ONS\sound\05_5.mp3]])
LSM:Register("sound", "|cff00ff006|r", [[Interface\Addons\SharedMedia_ONS\sound\06_6.mp3]])
LSM:Register("sound", "|cff00ff007|r", [[Interface\Addons\SharedMedia_ONS\sound\07_7.mp3]])
LSM:Register("sound", "|cff00ff008|r", [[Interface\Addons\SharedMedia_ONS\sound\08_8.mp3]])
LSM:Register("sound", "|cff00ff009|r", [[Interface\Addons\SharedMedia_ONS\sound\09_9.mp3]])
LSM:Register("sound", "|cff00ff0010|r", [[Interface\Addons\SharedMedia_ONS\sound\10_10.mp3]])

---------- Markers ------------
LSM:Register("sound", "|cff00ff00Skull|r", [[Interface\Addons\SharedMedia_ONS\sound\11_skull.mp3]])
LSM:Register("sound", "|cff00ff00Cross|r", [[Interface\Addons\SharedMedia_ONS\sound\12_cross.mp3]])
LSM:Register("sound", "|cff00ff00Square|r", [[Interface\Addons\SharedMedia_ONS\sound\13_Square.mp3]])
LSM:Register("sound", "|cff00ff00Moon|r", [[Interface\Addons\SharedMedia_ONS\sound\14_Moon.mp3]])
LSM:Register("sound", "|cff00ff00Triangle|r", [[Interface\Addons\SharedMedia_ONS\sound\15_Triangle.mp3]])
LSM:Register("sound", "|cff00ff00Diamond|r", [[Interface\Addons\SharedMedia_ONS\sound\16_Diamond.mp3]])
LSM:Register("sound", "|cff00ff00Circle|r", [[Interface\Addons\SharedMedia_ONS\sound\17_Circle.mp3]])
LSM:Register("sound", "|cff00ff00Star|r", [[Interface\Addons\SharedMedia_ONS\sound\18_Star.mp3]])

----------- Icons -------------
LSM:Register("sound", "|cff00ff00ADDS|r", [[Interface\Addons\SharedMedia_ONS\sound\20_Adds.mp3]])
LSM:Register("sound", "|cff00ff00AOE|r", [[Interface\Addons\SharedMedia_ONS\sound\21_AOE.mp3]])
LSM:Register("sound", "|cff00ff00Assist|r", [[Interface\Addons\SharedMedia_ONS\sound\22_Assist.mp3]])
LSM:Register("sound", "|cff00ff00Avoid|r", [[Interface\Addons\SharedMedia_ONS\sound\23_Avoid.mp3]])
LSM:Register("sound", "|cff00ff00Back|r", [[Interface\Addons\SharedMedia_ONS\sound\24_Back.mp3]])
LSM:Register("sound", "|cff00ff00Backup|r", [[Interface\Addons\SharedMedia_ONS\sound\25_Backup.mp3]])
LSM:Register("sound", "|cff00ff00Bait|r", [[Interface\Addons\SharedMedia_ONS\sound\26_Bait.mp3]])
LSM:Register("sound", "|cff00ff00Beam|r", [[Interface\Addons\SharedMedia_ONS\sound\27_Beam.mp3]])
LSM:Register("sound", "|cff00ff00Bloodlust|r", [[Interface\Addons\SharedMedia_ONS\sound\28_BloodLust.mp3]])
-- LSM:Register("sound", "|cff00ff00Blue|r", [[Interface\Addons\SharedMedia_ONS\sound\29_Blue.mp3]])
LSM:Register("sound", "|cff00ff00Boss|r", [[Interface\Addons\SharedMedia_ONS\sound\30_Boss.mp3]])
LSM:Register("sound", "|cff00ff00Break|r", [[Interface\Addons\SharedMedia_ONS\sound\31_Break.mp3]])
LSM:Register("sound", "|cff00ff00Buff|r", [[Interface\Addons\SharedMedia_ONS\sound\32_Buff.mp3]])
LSM:Register("sound", "|cff00ff00CC|r", [[Interface\Addons\SharedMedia_ONS\sound\33_CC.mp3]])
LSM:Register("sound", "|cff00ff00CD|r", [[Interface\Addons\SharedMedia_ONS\sound\34_CD.mp3]])
LSM:Register("sound", "|cff00ff00Center|r", [[Interface\Addons\SharedMedia_ONS\sound\35_Center.mp3]])
LSM:Register("sound", "|cff00ff00Chain|r", [[Interface\Addons\SharedMedia_ONS\sound\36_Chain.mp3]])
LSM:Register("sound", "|cff00ff00Charge|r", [[Interface\Addons\SharedMedia_ONS\sound\37_Charge.mp3]])
LSM:Register("sound", "|cff00ff00Clear|r", [[Interface\Addons\SharedMedia_ONS\sound\38_Clear.mp3]])
LSM:Register("sound", "|cff00ff00Collect|r", [[Interface\Addons\SharedMedia_ONS\sound\39_Collect.mp3]])
LSM:Register("sound", "|cff00ff00Collected|r", [[Interface\Addons\SharedMedia_ONS\sound\40_Collected.mp3]])
LSM:Register("sound", "|cff00ff00Dance|r", [[Interface\Addons\SharedMedia_ONS\sound\41_Dance.mp3]])
LSM:Register("sound", "|cff00ff00Debuff|r", [[Interface\Addons\SharedMedia_ONS\sound\42_Debuff.mp3]])
LSM:Register("sound", "|cff00ff00Dispel|r", [[Interface\Addons\SharedMedia_ONS\sound\43_Dispel.mp3]])
LSM:Register("sound", "|cff00ff00Dodge|r", [[Interface\Addons\SharedMedia_ONS\sound\44_Dodge.mp3]])
LSM:Register("sound", "|cff00ff00Dont Move|r", [[Interface\Addons\SharedMedia_ONS\sound\45_DontMove.mp3]])
LSM:Register("sound", "|cff00ff00DOT|r", [[Interface\Addons\SharedMedia_ONS\sound\46_DOT.mp3]])
LSM:Register("sound", "|cff00ff00DROP|r", [[Interface\Addons\SharedMedia_ONS\sound\47_DROP.mp3]])
LSM:Register("sound", "|cff00ff00ENTER|r", [[Interface\Addons\SharedMedia_ONS\sound\48_ENTER.mp3]])
LSM:Register("sound", "|cff00ff00ESCORT|r", [[Interface\Addons\SharedMedia_ONS\sound\49_ESCORT.mp3]])
LSM:Register("sound", "|cff00ff00EXIT|r", [[Interface\Addons\SharedMedia_ONS\sound\50_EXIT.mp3]])
LSM:Register("sound", "|cff00ff00Fixate|r", [[Interface\Addons\SharedMedia_ONS\sound\51_Fixate.mp3]])
LSM:Register("sound", "|cff00ff00Front|r", [[Interface\Addons\SharedMedia_ONS\sound\52_Front.mp3]])
LSM:Register("sound", "|cff00ff00Gate|r", [[Interface\Addons\SharedMedia_ONS\sound\53_Gate.mp3]])
LSM:Register("sound", "|cff00ff00Gather|r", [[Interface\Addons\SharedMedia_ONS\sound\54_Gather.mp3]])
LSM:Register("sound", "|cff00ff00Taunt|r", [[Interface\Addons\SharedMedia_ONS\sound\55_Taunt.mp3]])
LSM:Register("sound", "|cff00ff00GO|r", [[Interface\Addons\SharedMedia_ONS\sound\56_GO.mp3]])
LSM:Register("sound", "|cff00ff00Stop|r", [[Interface\Addons\SharedMedia_ONS\sound\57_Stop.mp3]])
LSM:Register("sound", "|cff00ff00Posion|r", [[Interface\Addons\SharedMedia_ONS\sound\58_Posion.mp3]])
LSM:Register("sound", "|cff00ff00Fire|r", [[Interface\Addons\SharedMedia_ONS\sound\59_Fire.mp3]])
LSM:Register("sound", "|cff00ff00Void Zone|r", [[Interface\Addons\SharedMedia_ONS\sound\60_VoidZone.mp3]])
LSM:Register("sound", "|cff00ff00Flare Bomb|r", [[Interface\Addons\SharedMedia_ONS\sound\61_FlareBomb.mp3]])
LSM:Register("sound", "|cff00ff00Feast Down|r", [[Interface\Addons\SharedMedia_ONS\sound\62_FeastDown.mp3]])
LSM:Register("sound", "|cff00ff00Buffs Missing|r", [[Interface\Addons\SharedMedia_ONS\sound\63_BuffsMissing.mp3]])
LSM:Register("sound", "|cff00ff00Soak|r", [[Interface\Addons\SharedMedia_ONS\sound\64_Soak.mp3]])
LSM:Register("sound", "|cff00ff00Dont Soak|r", [[Interface\Addons\SharedMedia_ONS\sound\65_DontSoak.mp3]])
LSM:Register("sound", "|cff00ff00Red|r", [[Interface\Addons\SharedMedia_ONS\sound\66_Red.mp3]])
LSM:Register("sound", "|cff00ff00Blue|r", [[Interface\Addons\SharedMedia_ONS\sound\67_Blue.mp3]])
LSM:Register("sound", "|cff00ff00Green|r", [[Interface\Addons\SharedMedia_ONS\sound\68_Green.mp3]])
LSM:Register("sound", "|cff00ff00Purple|r", [[Interface\Addons\SharedMedia_ONS\sound\69_Purple.mp3]])
LSM:Register("sound", "|cff00ff00Orange|r", [[Interface\Addons\SharedMedia_ONS\sound\70_Orange.mp3]])
LSM:Register("sound", "|cff00ff00White|r", [[Interface\Addons\SharedMedia_ONS\sound\71_White.mp3]])
LSM:Register("sound", "|cff00ff00Gray|r", [[Interface\Addons\SharedMedia_ONS\sound\72_Gray.mp3]])
LSM:Register("sound", "|cff00ff00Yellow|r", [[Interface\Addons\SharedMedia_ONS\sound\73_Yellow.mp3]])
LSM:Register("sound", "|cff00ff00Follow|r", [[Interface\Addons\SharedMedia_ONS\sound\74_Follow.mp3]])
LSM:Register("sound", "|cff00ff00Mount Up|r", [[Interface\Addons\SharedMedia_ONS\sound\75_MountUp.mp3]])
LSM:Register("sound", "|cff00ff00Personals|r", [[Interface\Addons\SharedMedia_ONS\sound\76_Personals.mp3]])
LSM:Register("sound", "|cff00ff00Health Stone|r", [[Interface\Addons\SharedMedia_ONS\sound\77_HealthStone.mp3]])
LSM:Register("sound", "|cff00ff00Health Pot|r", [[Interface\Addons\SharedMedia_ONS\sound\78_HealthPot.mp3]])
LSM:Register("sound", "|cff00ff00Stack|r", [[Interface\Addons\SharedMedia_ONS\sound\79_Stack.mp3]])
LSM:Register("sound", "|cff00ff00Freedom|r", [[Interface\Addons\SharedMedia_ONS\sound\80_Freedom.mp3]])
LSM:Register("sound", "|cff00ff00Immunity|r", [[Interface\Addons\SharedMedia_ONS\sound\81_Immunity.mp3]])
LSM:Register("sound", "|cff00ff00Immune|r", [[Interface\Addons\SharedMedia_ONS\sound\82_Immune.mp3]])
LSM:Register("sound", "|cff00ff00Go Out|r", [[Interface\Addons\SharedMedia_ONS\sound\83_GoOut.mp3]])
LSM:Register("sound", "|cff00ff00Trance Eat|r", [[Interface\Addons\SharedMedia_ONS\sound\84_TranceEat.mp3]])

LSM:Register("sound", "|cff00ff00Seeds|r", [[Interface\Addons\SharedMedia_ONS\sound\85_Seeds.mp3]])
LSM:Register("sound", "|cff00ff00Drop Seeds|r", [[Interface\Addons\SharedMedia_ONS\sound\86_DropSeeds.mp3]])
LSM:Register("sound", "|cff00ff00Collect Seeds|r", [[Interface\Addons\SharedMedia_ONS\sound\87_CollectSeeds.mp3]])
LSM:Register("sound", "|cff00ff00Corrupted Seeds|r", [[Interface\Addons\SharedMedia_ONS\sound\88_CorruptedSeeds.mp3]])
LSM:Register("sound", "|cff00ff00Shields|r", [[Interface\Addons\SharedMedia_ONS\sound\89_Shields.mp3]])
LSM:Register("sound", "|cff00ff00Shield Gone|r", [[Interface\Addons\SharedMedia_ONS\sound\90_ShieldGone.mp3]])
LSM:Register("sound", "|cff00ff00Shield Up|r", [[Interface\Addons\SharedMedia_ONS\sound\91_ShieldUp.mp3]])
LSM:Register("sound", "|cff00ff00Shield Down|r", [[Interface\Addons\SharedMedia_ONS\sound\92_ShieldDown.mp3]])
LSM:Register("sound", "|cff00ff00Stack|r", [[Interface\Addons\SharedMedia_ONS\sound\93_Stack.mp3]])
LSM:Register("sound", "|cff00ff00Danger|r", [[Interface\Addons\SharedMedia_ONS\sound\94_Danger.mp3]])
LSM:Register("sound", "|cff00ff00Beams Incoming|r", [[Interface\Addons\SharedMedia_ONS\sound\95_BeamsIncoming.mp3]])
LSM:Register("sound", "|cff00ff00Spread|r", [[Interface\Addons\SharedMedia_ONS\sound\96_Spread.mp3]])
LSM:Register("sound", "|cff00ff00Move|r", [[Interface\Addons\SharedMedia_ONS\sound\97_Move.mp3]])
LSM:Register("sound", "|cff00ff00Pull|r", [[Interface\Addons\SharedMedia_ONS\sound\98_Pull.mp3]])
LSM:Register("sound", "|cff00ff00Targeted|r", [[Interface\Addons\SharedMedia_ONS\sound\99_Targeted.mp3]])
LSM:Register("sound", "|cff00ff00Target|r", [[Interface\Addons\SharedMedia_ONS\sound\100_Target.mp3]])
LSM:Register("sound", "|cff00ff00Orbs|r", [[Interface\Addons\SharedMedia_ONS\sound\101_Orbs.mp3]])
LSM:Register("sound", "|cff00ff00Orb|r", [[Interface\Addons\SharedMedia_ONS\sound\102_Orb.mp3]])
LSM:Register("sound", "|cff00ff00Gravity Bomb|r", [[Interface\Addons\SharedMedia_ONS\sound\103_GravityBomb.mp3]])
LSM:Register("sound", "|cff00ff00Bozo|r", [[Interface\Addons\SharedMedia_ONS\sound\104_Bozo.mp3]])
LSM:Register("sound", "|cff00ff00You Died|r", [[Interface\Addons\SharedMedia_ONS\sound\105_YouDied.mp3]])
LSM:Register("sound", "|cff00ff00Phase Change|r", [[Interface\Addons\SharedMedia_ONS\sound\106_PhaseChange.mp3]])
LSM:Register("sound", "|cff00ff00Phasing|r", [[Interface\Addons\SharedMedia_ONS\sound\107_Phasing.mp3]])
LSM:Register("sound", "|cff00ff00Phase 1|r", [[Interface\Addons\SharedMedia_ONS\sound\108_PhaseOne.mp3]])
LSM:Register("sound", "|cff00ff00Phase 2|r", [[Interface\Addons\SharedMedia_ONS\sound\109_PhaseTwo.mp3]])
LSM:Register("sound", "|cff00ff00Phase 3|r", [[Interface\Addons\SharedMedia_ONS\sound\110_PhaseThree.mp3]])

------- V1.0.1 Sounds ------------
LSM:Register("sound", "|cff00ff00Intermission|r", [[Interface\Addons\SharedMedia_ONS\sound\111_Intermission.mp3]])
LSM:Register("sound", "|cff00ff00Intermission 1|r", [[Interface\Addons\SharedMedia_ONS\sound\112_IntermissionOne.mp3]])
LSM:Register("sound", "|cff00ff00Intermission 2|r", [[Interface\Addons\SharedMedia_ONS\sound\113_IntermissionTwo.mp3]])
LSM:Register("sound", "|cff00ff00Intermission 3|r", [[Interface\Addons\SharedMedia_ONS\sound\114_IntermissionThree.mp3]])
LSM:Register("sound", "|cff00ff00Fixated|r", [[Interface\Addons\SharedMedia_ONS\sound\115_Fixated.mp3]])
LSM:Register("sound", "|cff00ff00High Energy|r", [[Interface\Addons\SharedMedia_ONS\sound\116_HighEnergy.mp3]])
LSM:Register("sound", "|cff00ff00High Stacks|r", [[Interface\Addons\SharedMedia_ONS\sound\117_HighStacks.mp3]])
LSM:Register("sound", "|cff00ff00Hide|r", [[Interface\Addons\SharedMedia_ONS\sound\118_Hide.mp3]])
LSM:Register("sound", "|cff00ff00Transition|r", [[Interface\Addons\SharedMedia_ONS\sound\119_Transition.mp3]])
LSM:Register("sound", "|cff00ff00Switch|r", [[Interface\Addons\SharedMedia_ONS\sound\120_Switch.mp3]])
LSM:Register("sound", "|cff00ff00Stop Casting|r", [[Interface\Addons\SharedMedia_ONS\sound\121_StopCasting.mp3]])
LSM:Register("sound", "|cff00ff00Jump|r", [[Interface\Addons\SharedMedia_ONS\sound\122_Jump.mp3]])
LSM:Register("sound", "|cff00ff00Totem|r", [[Interface\Addons\SharedMedia_ONS\sound\123_Totem.mp3]])
LSM:Register("sound", "|cff00ff00Trap|r", [[Interface\Addons\SharedMedia_ONS\sound\124_Trap.mp3]])
LSM:Register("sound", "|cff00ff00Pushback|r", [[Interface\Addons\SharedMedia_ONS\sound\125_Pushback.mp3]])
LSM:Register("sound", "|cff00ff00Winds|r", [[Interface\Addons\SharedMedia_ONS\sound\126_Winds.mp3]])
LSM:Register("sound", "|cff00ff00Pull|r", [[Interface\Addons\SharedMedia_ONS\sound\127_Pull.mp3]])

--------- V1.1.1 Sounds -----------
LSM:Register("sound", "|cff00ff00Viranyr Get Away|r", [[Interface\Addons\SharedMedia_ONS\sound\128_GetAwayFromMe.mp3]])
LSM:Register("sound", "|cff00ff00Cheeky Rogue|r", [[Interface\Addons\SharedMedia_ONS\sound\129_PeksLaugh.mp3]])

--------- V1.1.2 Sounds -----------
LSM:Register("sound", "|cff00ff00Peks Sexy|r", [[Interface\Addons\SharedMedia_ONS\sound\130_SexyMan.mp3]])
LSM:Register("sound", "|cff00ff00Peks Fire|r", [[Interface\Addons\SharedMedia_ONS\sound\131_HotFire.mp3]])
-- LSM:Register("sound", "|cff00ff00Fox No|r", [[Interface\Addons\SharedMedia_ONS\sound\132_FoxNoo.mp3]])
LSM:Register("sound", "|cff00ff00Left|r", [[Interface\Addons\SharedMedia_ONS\sound\133_Left.mp3]])
LSM:Register("sound", "|cff00ff00Right|r", [[Interface\Addons\SharedMedia_ONS\sound\134_Right.mp3]])

--------- V1.1.4 Sounds -----------
LSM:Register("sound", "|cff00ff00Pushback|r", [[Interface\Addons\SharedMedia_ONS\sound\135_Pushback.mp3]])
LSM:Register("sound", "|cff00ff00Melee Soak|r", [[Interface\Addons\SharedMedia_ONS\sound\136_MeleeSoak.mp3]])
LSM:Register("sound", "|cff00ff00Ranged Soak|r", [[Interface\Addons\SharedMedia_ONS\sound\137_RangedSoak.mp3]])
LSM:Register("sound", "|cff00ff00Melee|r", [[Interface\Addons\SharedMedia_ONS\sound\138_Melee.mp3]])
LSM:Register("sound", "|cff00ff00Ranged|r", [[Interface\Addons\SharedMedia_ONS\sound\139_Ranged.mp3]])
LSM:Register("sound", "|cff00ff00Pain Suppression|r", [[Interface\Addons\SharedMedia_ONS\sound\140_PainSuppression.mp3]])
LSM:Register("sound", "|cff00ff00Barkskin|r", [[Interface\Addons\SharedMedia_ONS\sound\141_Barksin.mp3]])
LSM:Register("sound", "|cff00ff00Ironbark|r", [[Interface\Addons\SharedMedia_ONS\sound\142_Ironbark.mp3]])
LSM:Register("sound", "|cff00ff00Guardian Spirit|r", [[Interface\Addons\SharedMedia_ONS\sound\143_GuardianSpirit.mp3]])
LSM:Register("sound", "|cff00ff00Life Cocoon|r", [[Interface\Addons\SharedMedia_ONS\sound\144_LifeCocoon.mp3]])
LSM:Register("sound", "|cff00ff00Blessing of Protection|r",
    [[Interface\Addons\SharedMedia_ONS\sound\145_BlessingOfProtection.mp3]])
LSM:Register("sound", "|cff00ff00BOP|r", [[Interface\Addons\SharedMedia_ONS\sound\146_Bop.mp3]])
LSM:Register("sound", "|cff00ff00Spellward|r", [[Interface\Addons\SharedMedia_ONS\sound\147_SpellWard.mp3]])
LSM:Register("sound", "|cff00ff00Freedom|r", [[Interface\Addons\SharedMedia_ONS\sound\148_Freedom.mp3]])
LSM:Register("sound", "|cff00ff00Sacrifice|r", [[Interface\Addons\SharedMedia_ONS\sound\149_Sacrifice.mp3]])
LSM:Register("sound", "|cff00ff00Zephyr|r", [[Interface\Addons\SharedMedia_ONS\sound\150_Zephyr.mp3]])
LSM:Register("sound", "|cff00ff00Darkness|r", [[Interface\Addons\SharedMedia_ONS\sound\151_Darkness.mp3]])
LSM:Register("sound", "|cff00ff00Rally|r", [[Interface\Addons\SharedMedia_ONS\sound\152_Rally.mp3]])
LSM:Register("sound", "|cff00ff00Spirit Link|r", [[Interface\Addons\SharedMedia_ONS\sound\153_SpiritLink.mp3]])
LSM:Register("sound", "|cff00ff00Link|r", [[Interface\Addons\SharedMedia_ONS\sound\154_Link.mp3]])
LSM:Register("sound", "|cff00ff00Barrier|r", [[Interface\Addons\SharedMedia_ONS\sound\155_Barrier.mp3]])
LSM:Register("sound", "|cff00ff00Dome|r", [[Interface\Addons\SharedMedia_ONS\sound\156_Dome.mp3]])
LSM:Register("sound", "|cff00ff00Windrush|r", [[Interface\Addons\SharedMedia_ONS\sound\157_Windrush.mp3]])
LSM:Register("sound", "|cff00ff00Healing Tide|r", [[Interface\Addons\SharedMedia_ONS\sound\158_HealingTide.mp3]])
LSM:Register("sound", "|cff00ff00Tide|r", [[Interface\Addons\SharedMedia_ONS\sound\159_Tide.mp3]])
LSM:Register("sound", "|cff00ff00Grounding|r", [[Interface\Addons\SharedMedia_ONS\sound\160_Grounding.mp3]])
LSM:Register("sound", "|cff00ff00Tremor|r", [[Interface\Addons\SharedMedia_ONS\sound\161_Tremor.mp3]])
LSM:Register("sound", "|cff00ff00Dispel|r", [[Interface\Addons\SharedMedia_ONS\sound\162_Dispel.mp3]])
LSM:Register("sound", "|cff00ff00Purge|r", [[Interface\Addons\SharedMedia_ONS\sound\163_Purge.mp3]])
LSM:Register("sound", "|cff00ff00Tranqu|r", [[Interface\Addons\SharedMedia_ONS\sound\164_Tranqu.mp3]])
LSM:Register("sound", "|cff00ff00Revival|r", [[Interface\Addons\SharedMedia_ONS\sound\165_Revival.mp3]])
LSM:Register("sound", "|cff00ff00Aura Mastery|r", [[Interface\Addons\SharedMedia_ONS\sound\166_AuraMastery.mp3]])
LSM:Register("sound", "|cff00ff00AM|r", [[Interface\Addons\SharedMedia_ONS\sound\167_AM.mp3]])
LSM:Register("sound", "|cff00ff00Cheat Death|r", [[Interface\Addons\SharedMedia_ONS\sound\168_CheatDeath.mp3]])
LSM:Register("sound", "|cff00ff00Roar|r", [[Interface\Addons\SharedMedia_ONS\sound\169_Roar.mp3]])
LSM:Register("sound", "|cff00ff00Time Spiral|r", [[Interface\Addons\SharedMedia_ONS\sound\170_TimeSpiral.mp3]])
LSM:Register("sound", "|cff00ff00Rescue|r", [[Interface\Addons\SharedMedia_ONS\sound\171_Rescue.mp3]])
LSM:Register("sound", "|cff00ff00Leap|r", [[Interface\Addons\SharedMedia_ONS\sound\172_Leap.mp3]])
LSM:Register("sound", "|cff00ff00Mass Grip|r", [[Interface\Addons\SharedMedia_ONS\sound\173_MassGrip.mp3]])
LSM:Register("sound", "|cff00ff00Safe|r", [[Interface\Addons\SharedMedia_ONS\sound\174_Safe.mp3]])
LSM:Register("sound", "|cff00ff00Not Safe|r", [[Interface\Addons\SharedMedia_ONS\sound\175_NotSafe.mp3]])


----------- V1.1.5 Sounds -----------
LSM:Register("sound", "|cff00ff00Stone Form|r", [[Interface\Addons\SharedMedia_ONS\sound\176_StoneForm.mp3]])
LSM:Register("sound", "|cff00ff00Blaze|r", [[Interface\Addons\SharedMedia_ONS\sound\177_Blaze.mp3]])
LSM:Register("sound", "|cff00ff00Blaze Hit|r", [[Interface\Addons\SharedMedia_ONS\sound\178_BlazeHit.mp3]])
LSM:Register("sound", "|cff00ff00Cage|r", [[Interface\Addons\SharedMedia_ONS\sound\179_Cage.mp3]])
LSM:Register("sound", "|cff00ff00Nuke|r", [[Interface\Addons\SharedMedia_ONS\sound\180_Nuke.mp3]])
LSM:Register("sound", "|cff00ff00Tornado|r", [[Interface\Addons\SharedMedia_ONS\sound\181_Tornado.mp3]])
LSM:Register("sound", "|cff00ff00Bad Blaze|r", [[Interface\Addons\SharedMedia_ONS\sound\182_BadBlaze.mp3]])
LSM:Register("sound", "|cff00ff00Ducked|r", [[Interface\Addons\SharedMedia_ONS\sound\183_Ducked.mp3]])
LSM:Register("sound", "|cff00ff00Purple|r", [[Interface\Addons\SharedMedia_ONS\sound\184_Purple.mp3]])
LSM:Register("sound", "|cff00ff00Shadow|r", [[Interface\Addons\SharedMedia_ONS\sound\185_Shadow.mp3]])


----------- V1.1.8 Sounds -----------

LSM:Register("sound", "|cff00ff00Group Soak|r", [[Interface\Addons\SharedMedia_ONS\sound\186_GroupSoak.mp3]])
LSM:Register("sound", "|cff00ff00Lightning|r", [[Interface\Addons\SharedMedia_ONS\sound\187_Lightning.mp3]])
LSM:Register("sound", "|cff00ff00Lightning Soak|r", [[Interface\Addons\SharedMedia_ONS\sound\188_LightningSoak.mp3]])
LSM:Register("sound", "|cff00ff00Middle|r", [[Interface\Addons\SharedMedia_ONS\sound\189_Middle.mp3]])
LSM:Register("sound", "|cff00ff00Positive|r", [[Interface\Addons\SharedMedia_ONS\sound\190_Positive.mp3]])
LSM:Register("sound", "|cff00ff00Negative|r", [[Interface\Addons\SharedMedia_ONS\sound\191_Negative.mp3]])
LSM:Register("sound", "|cff00ff00Inversion|r", [[Interface\Addons\SharedMedia_ONS\sound\192_Inversion.mp3]])
LSM:Register("sound", "|cff00ff00Inverted|r", [[Interface\Addons\SharedMedia_ONS\sound\193_Inverted.mp3]])
LSM:Register("sound", "|cff00ff00Group|r", [[Interface\Addons\SharedMedia_ONS\sound\194_Group.mp3]])
LSM:Register("sound", "|cff00ff00Frontal|r", [[Interface\Addons\SharedMedia_ONS\sound\195_Frontal.mp3]])
LSM:Register("sound", "|cff00ff00Dance|r", [[Interface\Addons\SharedMedia_ONS\sound\196_Dance.mp3]])
LSM:Register("sound", "|cff00ff00Dance Soon|r", [[Interface\Addons\SharedMedia_ONS\sound\197_DanceSoon.mp3]])
LSM:Register("sound", "|cff00ff00Magnet|r", [[Interface\Addons\SharedMedia_ONS\sound\198_Magnet.mp3]])
LSM:Register("sound", "|cff00ff00Grip|r", [[Interface\Addons\SharedMedia_ONS\sound\199_Grip.mp3]])
LSM:Register("sound", "|cff00ff00Grip on Me|r", [[Interface\Addons\SharedMedia_ONS\sound\200_GripOnMe.mp3]])
LSM:Register("sound", "|cff00ff00Break Eggs|r", [[Interface\Addons\SharedMedia_ONS\sound\201_BreakEggs.mp3]])
LSM:Register("sound", "|cff00ff00Eggs|r", [[Interface\Addons\SharedMedia_ONS\sound\202_Eggs.mp3]])
LSM:Register("sound", "|cff00ff00Staff|r", [[Interface\Addons\SharedMedia_ONS\sound\203_Staff.mp3]])
LSM:Register("sound", "|cff00ff00Staff Spawning|r", [[Interface\Addons\SharedMedia_ONS\sound\204_StaffSpawning.mp3]])
LSM:Register("sound", "|cff00ff00Breath|r", [[Interface\Addons\SharedMedia_ONS\sound\205_Breath.mp3]])
LSM:Register("sound", "|cff00ff00Breath Soon|r", [[Interface\Addons\SharedMedia_ONS\sound\206_BreathSoon.mp3]])
LSM:Register("sound", "|cff00ff00Boss Immune|r", [[Interface\Addons\SharedMedia_ONS\sound\207_BossImmune.mp3]])
LSM:Register("sound", "|cff00ff00Black Hole|r", [[Interface\Addons\SharedMedia_ONS\sound\208_BlackHole.mp3]])
LSM:Register("sound", "|cff00ff00Ascension|r", [[Interface\Addons\SharedMedia_ONS\sound\209_Ascension.mp3]])
LSM:Register("sound", "|cff00ff00Ascension Soon|r", [[Interface\Addons\SharedMedia_ONS\sound\210_AscensionSoon.mp3]])
LSM:Register("sound", "|cff00ff00Detonation|r", [[Interface\Addons\SharedMedia_ONS\sound\211_Detonation.mp3]])
LSM:Register("sound", "|cff00ff00Ball|r", [[Interface\Addons\SharedMedia_ONS\sound\212_Ball.mp3]])
LSM:Register("sound", "|cff00ff00New Ball|r", [[Interface\Addons\SharedMedia_ONS\sound\213_NewBall.mp3]])
LSM:Register("sound", "|cff00ff00Essence|r", [[Interface\Addons\SharedMedia_ONS\sound\214_Essence.mp3]])
LSM:Register("sound", "|cff00ff00Spear|r", [[Interface\Addons\SharedMedia_ONS\sound\215_Spear.mp3]])
LSM:Register("sound", "|cff00ff00Dodge Waves|r", [[Interface\Addons\SharedMedia_ONS\sound\216_DodgeWaves.mp3]])
LSM:Register("sound", "|cff00ff00Waves|r", [[Interface\Addons\SharedMedia_ONS\sound\217_Waves.mp3]])
LSM:Register("sound", "|cff00ff00Absorbs|r", [[Interface\Addons\SharedMedia_ONS\sound\218_Absorbs.mp3]])
LSM:Register("sound", "|cff00ff00Disarm|r", [[Interface\Addons\SharedMedia_ONS\sound\219_Disarm.mp3]])
LSM:Register("sound", "|cff00ff00Bombs|r", [[Interface\Addons\SharedMedia_ONS\sound\220_Bombs.mp3]])
LSM:Register("sound", "|cff00ff00Traps|r", [[Interface\Addons\SharedMedia_ONS\sound\221_Traps.mp3]])
LSM:Register("sound", "|cff00ff00Magma|r", [[Interface\Addons\SharedMedia_ONS\sound\222_Magma.mp3]])
LSM:Register("sound", "|cff00ff00Tantrum|r", [[Interface\Addons\SharedMedia_ONS\sound\223_Tantrum.mp3]])
LSM:Register("sound", "|cff00ff00Knockback|r", [[Interface\Addons\SharedMedia_ONS\sound\224_Knockback.mp3]])
LSM:Register("sound", "|cff00ff00Break Wall|r", [[Interface\Addons\SharedMedia_ONS\sound\225_BreakWall.mp3]])
LSM:Register("sound", "|cff00ff00Corrupted|r", [[Interface\Addons\SharedMedia_ONS\sound\226_Corrupted.mp3]])
LSM:Register("sound", "|cff00ff00Mind Control|r", [[Interface\Addons\SharedMedia_ONS\sound\227_MindControl.mp3]])
LSM:Register("sound", "|cff00ff00Barrage|r", [[Interface\Addons\SharedMedia_ONS\sound\228_Barrage.mp3]])
LSM:Register("sound", "|cff00ff00Collect|r", [[Interface\Addons\SharedMedia_ONS\sound\229_Collect.mp3]])
LSM:Register("sound", "|cff00ff00Get Out|r", [[Interface\Addons\SharedMedia_ONS\sound\230_GetOut.mp3]])
LSM:Register("sound", "|cff00ff00Get In|r", [[Interface\Addons\SharedMedia_ONS\sound\231_GetIn.mp3]])

----------- V1.1.9 Sounds -----------
LSM:Register("sound", "|cff00ff00Go Far|r", [[Interface\Addons\SharedMedia_ONS\sound\232_GoFar.mp3]])
LSM:Register("sound", "|cff00ff00Far Away|r", [[Interface\Addons\SharedMedia_ONS\sound\233_FarAway.mp3]])
LSM:Register("sound", "|cff00ff00Place Far|r", [[Interface\Addons\SharedMedia_ONS\sound\234_PlaceFar.mp3]])
LSM:Register("sound", "|cff00ff00Soak Soon|r", [[Interface\Addons\SharedMedia_ONS\sound\235_SoakSoon.mp3]])
LSM:Register("sound", "|cff00ff00Soak Next|r", [[Interface\Addons\SharedMedia_ONS\sound\236_SoakNext.mp3]])
LSM:Register("sound", "|cff00ff00Volcanic Heart|r", [[Interface\Addons\SharedMedia_ONS\sound\237_VolcanicHeart.mp3]])
LSM:Register("sound", "|cff00ff00Volcanic|r", [[Interface\Addons\SharedMedia_ONS\sound\238_Volcanic.mp3]])
LSM:Register("sound", "|cff00ff00Raid Damage|r", [[Interface\Addons\SharedMedia_ONS\sound\239_RaidDamage.mp3]])
LSM:Register("sound", "|cff00ff00Big Aoe|r", [[Interface\Addons\SharedMedia_ONS\sound\240_BigAoe.mp3]])
LSM:Register("sound", "|cff00ff00Big Aoe Soon|r", [[Interface\Addons\SharedMedia_ONS\sound\241_BigAoeSoon.mp3]])
LSM:Register("sound", "|cff00ff00Fully Buffed|r", [[Interface\Addons\SharedMedia_ONS\sound\242_FullyBuffed.mp3]])
LSM:Register("sound", "|cff00ff00All Stacks|r", [[Interface\Addons\SharedMedia_ONS\sound\243_AllStacks.mp3]])
LSM:Register("sound", "|cff00ff00Max Stacks|r", [[Interface\Addons\SharedMedia_ONS\sound\244_MaxStacks.mp3]])


--------- v1.1.12 Sounds -----------
LSM:Register("sound", "|cff00ff00Max Stacks|r", [[Interface\Addons\SharedMedia_ONS\sound\244_MaxStacks.mp3]])
LSM:Register("sound", "|cff00ff00Earthen Wall|r", [[Interface\Addons\SharedMedia_ONS\sound\255_EarthernWall.mp3]]) --FIXME: Trigger is not working in game check file path
LSM:Register("sound", "|cff00ff00BOP|r", [[Interface\Addons\SharedMedia_ONS\sound\256_BOP.mp3]])
LSM:Register("sound", "|cff00ff00Blessing of Protection|r",
    [[Interface\Addons\SharedMedia_ONS\sound\257_BlessingOfProtection.mp3]])
LSM:Register("sound", "|cff00ff00Cocoon|r", [[Interface\Addons\SharedMedia_ONS\sound\258_Cocoon.mp3]])
LSM:Register("sound", "|cff00ff00AOE Incoming|r", [[Interface\Addons\SharedMedia_ONS\sound\259_AOEIncoming.mp3]])
LSM:Register("sound", "|cff00ff00Damage Reduction|r", [[Interface\Addons\SharedMedia_ONS\sound\260_DamageReduction.mp3]])
LSM:Register("sound", "|cff00ff00Fortitude|r", [[Interface\Addons\SharedMedia_ONS\sound\261_Fortitude.mp3]])
LSM:Register("sound", "|cff00ff00Stay Away From Lines|r",
    [[Interface\Addons\SharedMedia_ONS\sound\262_StayAwayFromLines.mp3]])
LSM:Register("sound", "|cff00ff00Stay Away From Others|r",
    [[Interface\Addons\SharedMedia_ONS\sound\263_StayAwayFromOthers.mp3]])
LSM:Register("sound", "|cff00ff00Watch Your Step|r", [[Interface\Addons\SharedMedia_ONS\sound\264_WatchYourStep.mp3]])
LSM:Register("sound", "|cff00ff00Watch Your Feet|r", [[Interface\Addons\SharedMedia_ONS\sound\265_WatchYourFeet.mp3]])
LSM:Register("sound", "|cff00ff00Keep Moving|r", [[Interface\Addons\SharedMedia_ONS\sound\266_KeepMoving.mp3]])
LSM:Register("sound", "|cff00ff00Stay In The Circle|r",
    [[Interface\Addons\SharedMedia_ONS\sound\267_StayInTheCircle.mp3]])
LSM:Register("sound", "|cff00ff00Place Gate|r", [[Interface\Addons\SharedMedia_ONS\sound\268_PlaceGate.mp3]])
LSM:Register("sound", "|cff00ff00Rolling Acid|r", [[Interface\Addons\SharedMedia_ONS\sound\269_RollingAcid.mp3]])
LSM:Register("sound", "|cff00ff00Infested|r", [[Interface\Addons\SharedMedia_ONS\sound\270_Infested.mp3]])
LSM:Register("sound", "|cff00ff00Infested Soon|r", [[Interface\Addons\SharedMedia_ONS\sound\271_InfestedSoon.mp3]])
LSM:Register("sound", "|cff00ff00Infested Spawn|r", [[Interface\Addons\SharedMedia_ONS\sound\272_InfestedSpawn.mp3]])
LSM:Register("sound", "|cff00ff00Strands|r", [[Interface\Addons\SharedMedia_ONS\sound\273_Strands.mp3]])
LSM:Register("sound", "|cff00ff00Experimental Dosage|r",
    [[Interface\Addons\SharedMedia_ONS\sound\274_ExperimentalDosage.mp3]])
LSM:Register("sound", "|cff00ff00Dosage|r", [[Interface\Addons\SharedMedia_ONS\sound\275_Dosage.mp3]])
LSM:Register("sound", "|cff00ff00Regicide|r", [[Interface\Addons\SharedMedia_ONS\sound\276_Regicide.mp3]])
LSM:Register("sound", "|cff00ff00Twilight Masacre|r", [[Interface\Addons\SharedMedia_ONS\sound\277_TwilightMasacre.mp3]])
LSM:Register("sound", "|cff00ff00Masacre|r", [[Interface\Addons\SharedMedia_ONS\sound\278_Masacre.mp3]])
LSM:Register("sound", "|cff00ff00Assasination|r", [[Interface\Addons\SharedMedia_ONS\sound\279_Assasination.mp3]])
LSM:Register("sound", "|cff00ff00Phase Blades|r", [[Interface\Addons\SharedMedia_ONS\sound\280_PhaseBlades.mp3]])
LSM:Register("sound", "|cff00ff00Blades|r", [[Interface\Addons\SharedMedia_ONS\sound\281_Blades.mp3]])
LSM:Register("sound", "|cff00ff00Decimate|r", [[Interface\Addons\SharedMedia_ONS\sound\282_Decimate.mp3]])
LSM:Register("sound", "|cff00ff00Queens Bane|r", [[Interface\Addons\SharedMedia_ONS\sound\283_QueensBane.mp3]])
LSM:Register("sound", "|cff00ff00Queens Bane A|r", [[Interface\Addons\SharedMedia_ONS\sound\284_QueensBaneA.mp3]])
LSM:Register("sound", "|cff00ff00Queens Bane B|r", [[Interface\Addons\SharedMedia_ONS\sound\285_QueensBaneB.mp3]])
LSM:Register("sound", "|cff00ff00Stay Away|r", [[Interface\Addons\SharedMedia_ONS\sound\286_StayAway.mp3]])
LSM:Register("sound", "|cff00ff00Macro|r", [[Interface\Addons\SharedMedia_ONS\sound\287_Macro.mp3]])
LSM:Register("sound", "|cff00ff00Press Macro|r", [[Interface\Addons\SharedMedia_ONS\sound\288_PressMacro.mp3]])
LSM:Register("sound", "|cff00ff00Macro Now|r", [[Interface\Addons\SharedMedia_ONS\sound\289_MacroNow.mp3]])
LSM:Register("sound", "|cff00ff00Maximum Stacks|r", [[Interface\Addons\SharedMedia_ONS\sound\290_MaximumStacks.mp3]])
LSM:Register("sound", "|cff00ff00Spinnerets|r", [[Interface\Addons\SharedMedia_ONS\sound\291_Spinnerets.mp3]])
LSM:Register("sound", "|cff00ff00Spinnerets Strands|r",
    [[Interface\Addons\SharedMedia_ONS\sound\292_SpinneretsStrands.mp3]])
LSM:Register("sound", "|cff00ff00Tethered|r", [[Interface\Addons\SharedMedia_ONS\sound\293_Tethered.mp3]])
LSM:Register("sound", "|cff00ff00Tether|r", [[Interface\Addons\SharedMedia_ONS\sound\294_Tether.mp3]])
LSM:Register("sound", "|cff00ff00Tether On You|r", [[Interface\Addons\SharedMedia_ONS\sound\295_TetherOnYou.mp3]])
LSM:Register("sound", "|cff00ff00Webs|r", [[Interface\Addons\SharedMedia_ONS\sound\296_Webs.mp3]])
LSM:Register("sound", "|cff00ff00Webbed|r", [[Interface\Addons\SharedMedia_ONS\sound\297_Webbed.mp3]])
LSM:Register("sound", "|cff00ff00Stay In Circle|r", [[Interface\Addons\SharedMedia_ONS\sound\298_StayInCircle.mp3]])
LSM:Register("sound", "|cff00ff00Peks Woo|r", [[Interface\Addons\SharedMedia_ONS\sound\299_PeksWoo.mp3]])
LSM:Register("sound", "|cff00ff00Morg You Suck|r", [[Interface\Addons\SharedMedia_ONS\sound\300_MorgYouSuck.mp3]])
LSM:Register("sound", "|cff00ff00Peks Clip Deeze Nuts|r",
    [[Interface\Addons\SharedMedia_ONS\sound\301_PeksClipDeezeNuts.mp3]])
LSM:Register("sound", "|cff00ff00Get A Rae From Me|r", [[Interface\Addons\SharedMedia_ONS\sound\302_GetARaeFromMe.mp3]])


--------- Version 1.1.14 Sounds ------------





--------- Random Sounds --------
LSM:Register("sound", "|cff55ee55Dark Souls Death|r", [[Interface\Addons\SharedMedia_ONS\sound\Z1_DarkSouls_Death.mp3]])
LSM:Register("sound", "|cff55ee55Skill Issue|r", [[Interface\Addons\SharedMedia_ONS\sound\Z2_SKillIssue.ogg]])
LSM:Register("sound", "|cff55ee55Jurassic Park|r", [[Interface\Addons\SharedMedia_ONS\sound\Z3_JurassicPark.ogg]])
LSM:Register("sound", "|cff55ee55Mega Pint|r", [[Interface\Addons\SharedMedia_ONS\sound\Z4_MegaPint.mp3]])
LSM:Register("sound", "|cff55ee55Daddy Chill|r", [[Interface\Addons\SharedMedia_ONS\sound\Z5_DaddyChill.mp3]])
LSM:Register("sound", "|cff55ee55Taa Daa|r", [[Interface\Addons\SharedMedia_ONS\sound\Z6_TaDa.mp3]])
LSM:Register("sound", "|cff55ee55Zelda Chest|r", [[Interface\Addons\SharedMedia_ONS\sound\Z7_ZeldaChest.mp3]])
LSM:Register("sound", "|cff55ee55Pedro|r", [[Interface\Addons\SharedMedia_ONS\sound\Z8_Pedro.mp3]])
LSM:Register("sound", "|cff55ee55Surf Bird|r", [[Interface\Addons\SharedMedia_ONS\sound\Z9_SurfBird.mp3]])
LSM:Register("sound", "|cff55ee55Another One|r", [[Interface\Addons\SharedMedia_ONS\sound\Z10_AnotherOne.mp3]])
LSM:Register("sound", "|cff55ee55Coffin Dance|r", [[Interface\Addons\SharedMedia_ONS\sound\Z11_CoffinDance.mp3]])
LSM:Register("sound", "|cff55ee55Why are you running?|r",
    [[Interface\Addons\SharedMedia_ONS\sound\Z12_WhyAreYouRunning.mp3]])
LSM:Register("sound", "|cff55ee55Phasomo Van|r", [[Interface\Addons\SharedMedia_ONS\sound\Z13_PhasmoVan.mp3]])

----------- Guild Meme Sounds --------

-- TODO - Create Categories for all of the sounds so they can easily be searched in game.
-- TODO - Add the in game Icon to the name of the markers.
